### ISSUE TITLE
Error encoding UTF-8 characters

### ISSUE THREAD

**Issue by mpldr** [digitorus/pdfsign#2]
![2023-03-02-09-19-14](https://user-images.githubusercontent.com/33086936/222371217-235e3c85-01e5-4e44-b617-e59151220206.png)

When adding a String with UTF-8 Symbols (for example in Location), it is shown as above.

**Comment by vanbroup** [comment]
I found a way that should resolve this, but without success, although the test file from the document below doesn't seem to work in my versions of Acrobat eighter.
https://www.pdfa.org/understanding-utf-8-in-pdf-2-0/

Can you try to download this test file and check if the document properties are shown correctly for you?
https://github.com/pdf-association/pdf20examples/raw/master/pdf20-utf8-test.pdf

**Comment by vanbroup** [comment]
It might actually better to use UTF-16 encoding, I will do some testing with that.

**Comment by vanbroup** [comment]
Text is now encoded with UTF-16BE encoding when required, this resolved the issue on my side, please check if your issue has been resolved for you as well.
