### ISSUE TITLE
Should the revocation.RevocationData expire?

### ISSUE THREAD

**Issue by karelbilek** [digitorus/pdfsign#22]
How does the RevocationData cache works?

Should it be cleared once in a while? Is there some expiry after which the OCSP response or CRL response is no longer valid?

In the EU checker, I see

>Is the current time in the validity range of the signer's certificate?

And there, I see the entire validity of the cert. So the OCSP response can always be reused, as long as the certificate stays the same? I think it can, just making sure

**Comment by karelbilek** [comment]
Hm, I also see the OCSP response has thisUpdate and nextUpdate thing. I am not sure if I should look at those or not.

The current codebase doesn't seem to look at them though

**Comment by karelbilek** [comment]
<img width="396" alt="Screenshot 2023-11-21 at 20 09 46" src="https://github.com/digitorus/pdfsign/assets/104945/923e073c-6cb4-443b-8e59-4f23ff9e5d74">

**Comment by karelbilek** [comment]
Acrobat shows the OCSP thisUpdate/nextUpdate here

<img width="404" alt="Screenshot 2023-11-21 at 20 11 38" src="https://github.com/digitorus/pdfsign/assets/104945/041580bc-cc1e-4386-a155-d1886625ed32">

I cannot try now what will happen if I use old one when trying to sign the document with newer timestamp. :/

**Comment by vanbroup** [comment]
It's best to use a fresh OCSP response (as close as possible to your signing time to ensure that the certificate was not revoked at the time of signing), the code does not cache the response, but you could do this if you have to sign a lot of documents in a batch. 

Most CAs do distribute OCSP responses through a Content Deliver Network (CDN) which will cache the response for a period of time. Only a few CAs support OCSP nonce to enforce a fresh request on every request.

**Comment by karelbilek** [comment]
Ah, I thought the `RevocationData` argument is a cache?

As I see this in readme

```
    // cache revocation data when bulk signing
```

However looking into source code it doesn't actually work as a cache :) and it's always re-downloaded even when it's there already
