### ISSUE TITLE
Signing PDF with annotations results in invalid signature

### ISSUE THREAD

**Issue by Twometer** [digitorus/pdfsign#50]
I have a PDF that was created with [gopdf](https://github.com/signintech/gopdf) and contains Link annotations.
The PDF is then signed with pdfsign.

If I open the signed document in Adobe, it reports:

> *Signature is invalid*: There have been changes made that invalidate the signature.

Without the link annotation, everything works fine and the PDF is shown as certified.

**Comment by vanbroup** [comment]
Can you add some examples code and the resulting PDF files?

**Comment by Twometer** [comment]
@vanbroup Sure:

## Working PDF
![image](https://github.com/user-attachments/assets/11d3f814-a57b-4d77-8f9a-24b5e7bbc4a1)
It says unknown because of my self-signed test certificate, but as you can see it says "Document has not been modified".

PDF download: [working.pdf](https://github.com/user-attachments/files/17628710/working.pdf)

## Failing PDF
![image](https://github.com/user-attachments/assets/95afdcb1-4bf3-40a3-8f83-60395e1d945c)
Here, it says "There have been changes made to this document that invalidate the signature.

The only difference is that a Link is now added to the PDF

PDF download:  [failing.pdf](https://github.com/user-attachments/files/17628713/failing.pdf)

## Repro

I am using this code for signing the PDF:
```go
pdfSign.Sign(bytes.NewReader(pdf), pdfWriter, pdfReader, pdfLen, pdfSign.SignData{
	Signature: pdfSign.SignDataSignature{
		CertType:   pdfSign.CertificationSignature,
		DocMDPPerm: pdfSign.AllowFillingExistingFormFieldsAndSignaturesAndCRUDAnnotationsPerms,
		Info: pdfSign.SignDataSignatureInfo{
			Name:        "Test Signing",
			Reason:      "Demonstrating signing failures",
			Location:    "The Internet",
			ContactInfo: "Twometer",
			Date:        time.Now(),
		},
	},

	DigestAlgorithm:   crypto.SHA384,
	Signer:            certs.key,
	Certificate:       certs.cert,
	CertificateChains: [][]*x509.Certificate{certs.chain},
})
```

Here is the repro code: https://gist.github.com/Twometer/d6611dee04132251531fbc2962190388

## More info

The only difference I can see in those PDFs raw streams is the line

```
/Annots [<</Type /Annot /Subtype /Link /Rect [0.00 842.00 32.00 810.00] /Border [0 0 0] /A <</S /URI /URI (https://google.com)>>>>]
```

being present in the Page object.

(And of course some changes to the signature and the xref table)

**Comment by vanbroup** [comment]
Thanks for these details @Twometer. I couldn’t find your unsigned file right away, but I’ve just released a new version that should address your issue. Could you please verify if it works?

**Comment by Twometer** [comment]
Thanks @vanbroup, I have just tested the new version (`v0.0.0-20241114132424-1f5035cb0e1e`) with the same code and the same thing still happens:

![image](https://github.com/user-attachments/assets/6812817c-17c2-4cd4-8d88-cbbaa0ab8e74)

Do I have to change any settings in the signing configuration?

The unsigned file is created dynamically in the repro code with gopdf, but i've also attached it here: [failing-unsigned.pdf](https://github.com/user-attachments/files/17778137/failing-unsigned.pdf)

**Comment by Twometer** [comment]
okay one more update, I have tried setting `ApprovalSignature` instead of `CertificationSignature` and that seems to work now:

![image](https://github.com/user-attachments/assets/3be9981d-9488-4cdb-9871-c6dfc2a18567)

Do you have an idea why changing the signature type would "fix" this?

**Comment by Twometer** [comment]
I've noticed today that when viewing the document with an ApprovalSignature that Adobe shows as correctly signed using the Foxit PDF reader, it now complains that the document was corrupted:

![foxitSigningError](https://github.com/user-attachments/assets/08b8f8f2-f4e6-4a81-a4af-978276d8c3a3)

**Comment by vanbroup** [comment]
This doesn't happen with any of the test documents right? 

I have not been able to look at your source document yet but have you tried opening that with Acrobat and does it ask you to have the document when closing (this often happens when there is an issue in the source document).

Also, do you know if the document has an xref table or stream? I did do most testing with the tables and less with the streams for now.

**Comment by Twometer** [comment]
The only difference I can see between the test document and my document is that the `/Annots` object is inline in my document, but a reference to a separate object in the test document.

**Comment by arjen-ag5** [comment]
I have the exact same problem, any progress on this issue? My PDF Is also generated with gopdf, and fails when there is a link annotation in the PDF.

**Comment by vanbroup** [comment]
The signature has been invalidated because Adobe is repairing the original document.

As @Twometer noted, the page annotations created by [gopdf](https://github.com/signintech/gopdf) are written as an embedded annotation that needs to be an indirect reference instead:

```pdf
10 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /Resources 4 0 R
  /Annots [<</Type /Annot /Subtype /Link /Rect [0.00 842.00 32.00 810.00] /Border [0 0 0] /A <</S /URI /URI (https://google.com)>>>>]
  /Contents  11 0 R 
>>
endobj
```

![image](https://github.com/user-attachments/assets/d96dc9cd-a51a-4b13-875a-1541679a7fe6)

> An array of annotation dictionaries that shall contain indirect references to all annotations associated with the page (see 12.5, "Annotations").

**Comment by Twometer** [comment]
@vanbroup I have found the same paragraph in the spec, so I forked gopdf to write the annotations object correctly but I still got the same error message.

**Comment by vanbroup** [comment]
Do you have a copy of the file with the correct PDF syntax?

**Comment by oneplus1000** [comment]
So that mean  "/Annots" are not the root of the issue?

**Comment by Twometer** [comment]
I just found out that Foxit Reader still complains about the signature, even with the fixed Annotations:
![image](https://github.com/user-attachments/assets/fe58558f-220c-4162-9032-2cac85d3bf6a)

However, I think this may be an issue with Foxit, since it also complains without any annotations.

**Comment by vanbroup** [comment]
I can't remember that Foxit Reader complained about any other signed documents. Is it only with the file created by gopdf?

**Comment by Twometer** [comment]
I tried it with `testfile12.pdf` from your repository, and while Adobe shows it as correctly signed, Foxit does not show it as signed at all.

So Foxit at least has weird behavior also on signed non-gopdf files.

**Comment by vanbroup** [comment]
Let me investigate any issues with Foxit Reader, it used to validate correctly.

**Comment by vanbroup** [comment]
@Twometer please check with the lasted version

Foxit:
![image](https://github.com/user-attachments/assets/e8889494-e35a-4ae1-a552-401e3735ecf2)

Acrobat:
![image](https://github.com/user-attachments/assets/4310be29-4968-4256-84e5-fac4cce58660)

**Comment by Twometer** [comment]
@vanbroup 
![image](https://github.com/user-attachments/assets/9885cbbc-5a30-46be-897b-d4afe03b9223)
It works! Thank you very much
